### ISSUE TITLE
hotspot_jre_2 failures jdk8 arm32 hotspot

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3297]
3 tests from hotspot_jre_2 in the extended openjdk test suite fail on jdk8 arm32
Failure link https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/27/
Trss link https://trss.adoptium.net/output/test?id=61f04ed3a7df1a292406cf69

`compiler/gcbarriers/PreserveFPRegistersTest.java.PreserveFPRegistersTest`
Error log
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.ArithmeticException: / by zero
	at PreserveFPRegistersTest.<init>(PreserveFPRegistersTest.java:66)
	at PreserveFPRegistersTest.main(PreserveFPRegistersTest.java:39)
```

`gc/TestMemoryMXBeansAndPoolsPresence.java.TestMemoryMXBeansAndPoolsPresence`
```
OpenJDK Client VM warning: G1 GC is disabled in this release.
java.lang.RuntimeException: Expected 0 to equal 1
at com.oracle.java.testlibrary.Asserts.error(Asserts.java:450)
at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
```

`gc/g1/mixedgc/TestOldGenCollectionUsage.java.TestOldGenCollectionUsage`
Error log:
```
17:02:26  OpenJDK Client VM warning: G1 GC is disabled in this release.
17:02:26  java.lang.RuntimeException: G1 Old Gen not found, test with -XX:+UseG1GC
17:02:26  	at TestOldGenCollectionUsage.run(TestOldGenCollectionUsage.java:82)
```

Rerunning https://ci.adoptopenjdk.net/job/Grinder/3349/console

**Comment by Haroon-Khel** [comment]
Rerunning `gc/g1/mixedgc/TestOldGenCollectionUsage.java` with -XX:+UseG1GC https://ci.adoptopenjdk.net/job/Grinder/3363/console

**Comment by Haroon-Khel** [comment]
Still fails with the same error. Looking back at the trss link, `-XX:+UseG1GC` was already being used as an option
```
[2022-01-25T11:41:53.504Z]         -Xbootclasspath/a:. \
[2022-01-25T11:41:53.504Z]         -XX:+UseG1GC \
[2022-01-25T11:41:53.504Z]         -XX:+UnlockExperimentalVMOptions \
```

**Comment by Haroon-Khel** [comment]
https://bugs.openjdk.java.net/browse/JDK-8028772 is the closes I could find to a relevant upstream issue; it is simply a discussion of whether G1GC tests should be excluded. Not sure if that is enough to consider these failures to be non blocking

**Comment by sxa** [comment]
Do those tests fail when run against the last GA release? (8u312)?

**Comment by Haroon-Khel** [comment]
Rerunning with last GA release

`compiler/gcbarriers/PreserveFPRegistersTest.java.PreserveFPRegistersTest`
https://ci.adoptopenjdk.net/job/Grinder/3375/console

`gc/TestMemoryMXBeansAndPoolsPresence.java.TestMemoryMXBeansAndPoolsPresence`
https://ci.adoptopenjdk.net/job/Grinder/3376/console

`gc/g1/mixedgc/TestOldGenCollectionUsage.java`
https://ci.adoptopenjdk.net/job/Grinder/3377/console

**Comment by Haroon-Khel** [comment]
The warning and error for `gc/g1/mixedgc/TestOldGenCollectionUsage.java` are interesting. 
```
12:56:32  OpenJDK Client VM warning: G1 GC is disabled in this release.
12:56:32  java.lang.RuntimeException: G1 Old Gen not found, test with -XX:+UseG1GC
12:56:32  	at TestOldGenCollectionUsage.run(TestOldGenCollectionUsage.java:82)
```
If the test cannot find G1 because it has been disabled, then shouldn't this test be excluded?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3297#issuecomment-1025762334 - we will **not block release** due to these failures (as its shown, not a regression, that we have already released last GA binaries that fail in the same way).  

This isn't to say we do not need to do further investigation to understand what next action to take, as these will continue to fail.   I have not looked closely at all, but @Haroon-Khel when you look at the test code that prints out the `test with -XX:+UseG1GC` is there any indication why it actually ignores the fact that the option is already being set? I ran a Grinder with EXTRA_OPTION=-XX:+UseG1GC and see that it does ignore it.

**Comment by Haroon-Khel** [comment]
@ShelleyLambert Looking at https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/2544d2a351eca1a3d62276f969dd2d95e4a4d2b6/hotspot/test/gc/g1/mixedgc/TestOldGenCollectionUsage.java#L82, nothing suggests that the option is being ignored. I think that option is being ignored by the jdk and not by the test code. 

Do we know why G1 GC is disabled?
`12:56:32  OpenJDK Client VM warning: G1 GC is disabled in this release.`

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3297#issuecomment-1026761384 - sounds like we need a smoke test and a confirmation on which platforms/versions that feature is available in (much like we do for ZGC and Shenandoah features and smoke tests).  If its not available on this platform, tests expecting it should certainly be excluded (and expectation it would happen in upstream problem lists, but we can do that in our problem lists first).

**Comment by Haroon-Khel** [comment]
After @sxa's suggestion, rerunning `gc/g1/mixedgc/TestOldGenCollectionUsage.java` with https://github.com/adoptium/aarch32-jdk8u as the `JDK_REPO` parameter https://ci.adoptopenjdk.net/job/Grinder/3394/console

**Comment by Haroon-Khel** [comment]
The test still fails, but with an error which suggests that it was able to actually run the test 

```
13:55:51  OpenJDK Client VM warning: G1 GC is disabled in this release.
13:55:51  java.lang.RuntimeException: Expected 0 to equal 1
13:55:51  	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:450)
13:55:51  	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
13:55:51  	at com.oracle.java.testlibrary.Asserts.assertEquals(Asserts.java:169)
13:55:51  	at com.oracle.java.testlibrary.Asserts.assertEquals(Asserts.java:152)
```
So perhaps this test does not need to be excluded, but we do need to make sure that the right `JDK_REPO` parameter is used

**Comment by smlambert** [comment]
Yes, as discussed and lost in a Slack thread somewhere, because this platform is built from a special repo, the build pipeline should get triggered with USE_TESTENV_PROPERTIES=false, so that the test pipelines will use the correct JDK_REPO and the the RELEASE tag of it.

**Comment by sophia-guo** [comment]
Running with release tag got the same failures

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4615/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4616/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4617/
